// <auto-generated />
namespace UpComingGibs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialDBModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialDBModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201701010034107_initialDBModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
